title = "Article Time"
baseURL = "http://localhost:1313/"
languageCode = "de-DE"
theme = "article"

enableRobotsTXT = true
enableGitInfo = true
lastmod = [":git", "lastmod", "date"] 

DefaultContentLanguage = "de"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
# summaryLength = 45
copyright = "Design/Programmierung: <a href=\"https://angel-crawford.de/\" target=\"_blank\">Angel Crawford</a>"
[Author]
  name = "Angel Crawford"
  email = "email@mail.de"

[sitemap]
  changefreq = "weekly"
  priority = "0.9"
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  category = "categories"
  series = "series"
  contains = "contains"
  author = "authors"

[permalinks]
  articles = "/:section/:year/:month/:slug/"
  year = "/articles/:slug/"
  month = "/articles/:slug/"

[imaging]
  # Default JPEG quality setting. Default is 75.
  quality = 75

  # Default background color.
  # Hugo will preserve transparency for target formats that supports it,
  # but will fall back to this color for JPEG.
  # Expects a standard HEX color string with 3 or 6 digits.
  # See https://www.google.com/search?q=color+picker
  bgColor = "#ffffff"

  [imaging.exif]
    # Hugo extracts the "photo taken" date/time into .Date by default.
    disableDate = true

    # Hugo extracts the "photo taken where" (GPS latitude and longitude) into
    disableLatLong = true

[related]
  threshold = 0 
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

[params]
  author = "Angel Crawford"
  favicon = "favicon.ico"
  description = "The last theme you'll ever need. Maybe. dsds"

  [params.seo]
    twitterHandle = "crawford_ftw" #Twitter name, to bind shared cards to your profile
    keywords = "Webcard, Profil Karte, Angel Crawford"

  [[params.social]]
    name = "Facebook"
    link = "#"
    icon = "facebook-circle-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "twitter-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "Instagram"
    link = "#"
    icon = "instagram-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "Github"
    link = "#"
    icon = "github-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "RSS"
    link = "/index.xml"
    icon = "rss-line"
    inHeader = true
    inFooter = true

  [[params.categoryColor]]
    name = "Movie"
    color = "#537fbd"
  [[params.categoryColor]]
    name = "Kategorie 1"
    color = "green"
  [[params.categoryColor]]
    name = "Allgemein"
    color = "#cb282e"
  
  [params.csp]
    fontsrc = ["'self'", 
      "https://fonts.gstatic.com", 
      "disqus.com", 
      "disquscdn.com", 
      "*.disqus.com", 
      "*.disquscdn.com"]
    formaction = ["'self'",
      "https://syndication.twitter.com/",
      "https://platform.twitter.com",
      "disqus.com disquscdn.com",
      "*.disqus.com",
      "*.disquscdn.com"]
    framesrc = ["'self'",
      "https://player.vimeo.com",
      "www.youtube.com",
      "www.youtube-nocookie.com",
      "https://platform.twitter.com",
      "https://syndication.twitter.com",
      "jsfiddle.net",
      "www.instagram.com",
      "https://www.google.com",
      "disqus.com",
      "disquscdn.com",
      "*.disqus.com",
      "*.disquscdn.com"]
    imgsrc = ["'self'"]
    objectsrc = ["'none'"]
    stylesrc = ["'self'",
      "'unsafe-inline'",
      "https://fonts.googleapis.com",
      "https://www.google.com",
      "https://platform.twitter.com",
      "*.twimg.com",
      "disqus.com",
      "disquscdn.com",
      "*.disqus.com",
      "*.disquscdn.com"]
    scriptsrc = ["'self'",
      "'unsafe-inline'",
      "ws://localhost:1313/livereload",
      "https://platform.twitter.com",
      "https://cdn.syndication.twimg.com",
      "https://www.google-analytics.com",
      "cse.google.com",
      "https://www.google.com",
      "https://www.googletagservices.com",
      "jsfiddle.net",
      "www.instagram.com",
      "disqus.com",
      "disquscdn.com",
      "*.disqus.com",
      "*.disquscdn.com"]

  [params.staticman]
    endpoint = "https://article-static.herokuapp.com/v2/entry"
    username = "AngelCrawford"
    repository = "blog"
    branch = "master"
    gravatarDefault = "https://raw.githubusercontent.com/AngelCrawford/blog/master/themes/article/static/images/avatar.png"